name: Internal Continuous Integration
on:
  push:
    branches:
      - master
  pull_request:
env:
  MAKEFLAGS: '-j32'

jobs:
  n0100:
    runs-on: self-hosted
    steps:
      - run: sudo apt-get install build-essential imagemagick libfreetype6-dev libjpeg-dev libpng-dev pkg-config
      - run: pip3 install lz4 pypng stringcase
      - uses: numworks/setup-arm-toolchain@2021-10
      - uses: actions/checkout@v2
      - run: make MODEL=n0100 epsilon.dfu
      - run: make MODEL=n0100 epsilon.onboarding.beta.dfu
      - run: make MODEL=n0100 epsilon.onboarding.update.dfu
      - run: make MODEL=n0100 test.dfu
  n0110:
    runs-on: self-hosted
    steps:
      - run: sudo apt-get install build-essential imagemagick libfreetype6-dev libjpeg-dev libpng-dev pkg-config
      - run: pip3 install lz4
      - uses: numworks/setup-arm-toolchain@2020-q4
      - uses: actions/checkout@v2
      - run: make MODEL=n0110 kernel.A.elf
      - run: make MODEL=n0110 userland.A.elf
      - run: make MODEL=n0110 userland.onboarding.beta.A.elf
      - run: make MODEL=n0110 userland.onboarding.update.A.elf
      - run: make MODEL=n0110 userland.test.A.elf
      - run: make MODEL=n0110 kernel.B.elf
      - run: make MODEL=n0110 userland.B.elf
      - run: make MODEL=n0110 userland.test.B.elf
      - run: make MODEL=n0110 flasher.dfu
      - run: make MODEL=n0110 bench.ram.dfu
  linux:
    runs-on: self-hosted
    steps:
      - run: sudo apt-get install build-essential imagemagick libfreetype6-dev libjpeg-dev libpng-dev pkg-config
      - run: pip3 install lz4
      - uses: actions/checkout@v2
      - run: make PLATFORM=simulator
      - run: make PLATFORM=simulator epsilon.bin
      - run: make PLATFORM=simulator test.bin
      - run: output/release/simulator/linux/test.bin --headless --limit-stack-usage
  web:
    runs-on: self-hosted
    steps:
      - uses: numworks/setup-emscripten@v1
        with:
          sdk: 1.39.16-fastcomp
      - run: pip3 install lz4
      - uses: actions/checkout@v2
      - run: make PLATFORM=simulator TARGET=web
      - run: make PLATFORM=simulator TARGET=web epsilon.zip
      - run: make PLATFORM=simulator TARGET=web test.js
      - run: timeout 5m node output/release/simulator/web/test.js --headless --limit-stack-usage
