name: Internal Continuous Integration
on:
  push:
    branches:
      - master
  pull_request:
env:
  MAKEFLAGS: '-j32'
  ACCEPT_OFFICIAL_TOS: 1

jobs:
  n0100:
    runs-on: self-hosted
    steps:
      - uses: numworks/setup-arm-toolchain@2020-q4
      - uses: actions/checkout@v2
      - run: make MODEL=n0100 epsilon.dfu test.elf
  n0110:
    runs-on: self-hosted
    steps:
      - uses: numworks/setup-arm-toolchain@2020-q4
      - uses: actions/checkout@v2
      - run: make epsilon.dfu test.elf
  linux:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: make PLATFORM=simulator epsilon.bin test.bin
      - run: output/release/simulator/linux/test.bin --headless --limit-stack-usage
  web:
    runs-on: self-hosted
    steps:
      - uses: numworks/setup-emscripten@v1
        with:
          sdk: 1.39.16-fastcomp
      - uses: actions/checkout@v2
      - run: make PLATFORM=simulator TARGET=web
      - run: make PLATFORM=simulator TARGET=web epsilon.official.zip
      - run: make PLATFORM=simulator TARGET=web test.js
      - run: node output/release/simulator/web/test.js --headless --limit-stack-usage
