name: Internal Continuous Integration
on:
  push:
    branches:
      - master
  pull_request:
env:
  MAKEFLAGS: '-j32'
  ACCEPT_OFFICIAL_TOS: 1

jobs:
  n0100:
    runs-on: self-hosted
    steps:
      - uses: numworks/setup-arm-toolchain@2020-q4
      - uses: actions/checkout@v2
      - run: make MODEL=n0100 epsilon.dfu
      - run: make MODEL=n0100 epsilon.official.onboarding.beta.dfu
      - run: make MODEL=n0100 epsilon.official.onboarding.update.dfu
      - run: make MODEL=n0100 test.dfu
  n0110:
    runs-on: self-hosted
    steps:
      - uses: numworks/setup-arm-toolchain@2020-q4
      - uses: actions/checkout@v2
      - run: make MODEL=n0110 kernel.A.elf
      - run: make MODEL=n0110 userland.A.elf
      - run: make MODEL=n0110 userland.official.onboarding.beta.A.elf
      - run: make MODEL=n0110 userland.official.onboarding.update.A.elf
      - run: make MODEL=n0110 userland.test.A.elf
      - run: make MODEL=n0110 kernel.B.elf
      - run: make MODEL=n0110 userland.B.elf
      - run: make MODEL=n0110 userland.test.B.elf
      - run: make MODEL=n0110 flasher.dfu
      - run: make MODEL=n0110 bench.ram.dfu
  linux:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: make PLATFORM=simulator epsilon.bin test.bin
      - run: timeout 5m output/release/simulator/linux/test.bin --headless --limit-stack-usage
  web:
    runs-on: self-hosted
    steps:
      - uses: numworks/setup-emscripten@v1
        with:
          sdk: 1.39.16-fastcomp
      - uses: actions/checkout@v2
      - run: make PLATFORM=simulator TARGET=web
      - run: make PLATFORM=simulator TARGET=web epsilon.official.zip
      - run: make PLATFORM=simulator TARGET=web test.js
      - run: timeout 5m node output/release/simulator/web/test.js --headless --limit-stack-usage
