name: Internal Metrics
on: [pull_request_target]
env:
  MAKEFLAGS: '-j32'

jobs:
  binary-size:
    runs-on: self-hosted
    steps:
      - name: Install ARM toolchain
        uses: numworks/setup-arm-toolchain@2020-q4
      - name: Checkout PR base
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.base.sha }}
          path: base
      - name: Build base
        run: make -C base epsilon.elf
      - name: Checkout PR head
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          path: head
      - name: Build head
        run: make -C head epsilon.elf
      - name: Retrieve binary size analysis
        id: binary_size
        run: echo "::set-output name=table::$(python3 head/build/metrics/binary_size.py base/output/release/device/n0110/epsilon.elf head/output/release/device/n0110/epsilon.elf --labels Base Head --sections .text .rodata .bss .data --escape)"
      - name: Add comment
        uses: actions/github-script@v3.0.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            await github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: `${{ steps.binary_size.outputs.table }}`,
            });
